Update gradle-publish.yml

diff --git a/.github/workflows/gradle-publish.yml b/.github/workflows/gradle-publish.yml
--- a/.github/workflows/gradle-publish.yml
+++ b/.github/workflows/gradle-publish.yml
@@ -1,44 +1,59 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
-# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle
-
-name: Gradle Package
+name: Create release and upload binaries
 
 on:
-  release:
-    types: [created]
+  push:
+    tags:
+      - "v[0-9]+.[0-9]+.[0-9]*"
+
+  workflow_dispatch:
+
+permissions:
+  contents: write
 
 jobs:
-  build:
-
+  release:
+    name: Build release binaries
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
-        settings-path: ${{ github.workspace }} # location for the settings.xml file
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          submodules: true
+      
+      - name: Setup JDK
+        uses: actions/setup-java@v1
+        with:
+          java-version: 11
 
-    - name: Setup Gradle
-      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
+      - name: Update version 
+        run: |
+          tag=${GITHUB_REF#refs/tags/}
+          regex="v([0-9]+\.[0-9]+\.[0-9]+).*"
+          if [[ $tag =~ $regex ]]; then
+            extracted_version="${BASH_REMATCH[1]}"
+            echo "Extracted version: $extracted_version"
+          else
+            echo "Extracted version failed"
+            exit 1
+          fi
+          
+          sed -i "s/^version=.*/version=${tag}/" src/main/resources/plugin-descriptor.properties
+          sed -i "s/elasticsearch.version=.*/elasticsearch.version=${extracted_version}/" src/main/resources/plugin-descriptor.properties
+          sed -i "s/^version.*/version='${tag}'/" build.gradle
+          sed -i "s/org.elasticsearch:elasticsearch:.*/org.elasticsearch:elasticsearch:${extracted_version}'/" build.gradle
 
-    - name: Build with Gradle
-      run: ./gradlew build
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v2
+        with:
+          gradle-version: 7.6
 
-    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
-    # the publishing section of your build.gradle
-    - name: Publish to GitHub Packages
-      run: ./gradlew publish
-      env:
-        USERNAME: ${{ github.actor }}
-        TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build with Gradle
+        run: gradle pz
+
+      - name: Add Artifacts to Release
+        uses: softprops/action-gh-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
+        with:
+          files: build/distributions/*.zip
